### PR TITLE
Implemented WATERMeDIA

### PR DESCRIPTION
**Pull request by SrRapero720**
## Changes
- Added WATERMeDIA 1.3.x as dependency (using cursemaven)
- Removed VLCJ dependency
- Removed VLC Discovery (WATERMeDIA discovers itself)
- Ported FrameVideoDisplay to use VideoLANPlayer
- Removed GifDecoder (and replaced with WATERMeDIA one)
- Replaced VLC Error pictures with WATERMeDIA error pictures (x32 is deprecated on MC 1.17+)
- Replaced ``tick * 50`` with WaterMediaAPI.gameTicksToMs()
- Replaced/Deleted `TextureCache.uploadFrame()` with `WaterMediaAPI.preRender()`
- Replaced/Deleted ``TextureCache`` with `LocalStorage`
- Minor code fixes (making params as constants params)
- Replaced/Deleted `TextureSeeker` with `PictureFetcher` (this allow to use all WATERMeDIA's URL patcher, so pictures from GoogleDrive, DropBox or OneDrive can be openned)
- Fixed whitelist broken label
- (Contribution) added translation es_mx.json

## Information
VideoDisplay doesn't works with streams, playback is stepped, thats because this code cant detect some .m3u8 streams... specially twitch or kick.com streams

this bug is present on old versions... (extracting stream links manually)
https://github.com/CreativeMD/LittleFrames/blob/d4de643b6313effa0e919bc58fa25dd5f1875764/src/main/java/team/creative/littleframes/client/display/FrameVideoDisplay.java#L171

### CODE REVIEW

**Comment by SrRapero720** [comment]
## TESTING WITH YOUTUBE VIDEOS
2023-07-07_16h41_48
2023-07-07_16h41_43

## FORCED DISABLE VLC (how error picture looks)
2023-07-07_16h37_46

**Comment by SrRapero720** [comment]
Fixes #52 and #53

**Comment by CreativeMD** [comment]
Yeah, it is tricky to make it work with streaming, because they work in weird ways. This line: https://github.com/CreativeMD/LittleFrames/blob/d4de643b6313effa0e919bc58fa25dd5f1875764/src/main/java/team/creative/littleframes/client/display/FrameVideoDisplay.java#L171
worked in the past. This should be no difference when using watermedia, right? I'm a bit confused about this part.

**Comment by SrRapero720** [comment]
I Made few test but isn't working anymore. Is not caused by watermedia, probably Is how kick.com or twitch.com streams works

All streams plays with "lag" (got stunned trying to sync position)
I add the comment in any case someone report that bug

**Comment by SrRapero720** [comment]
I use ``VideoLANPlayer#isStream`` to avoid that. but is a unsafe method (WMedia 1.3.3). because every m3u8 stream is detected as stream, but for example twitch VODs aren't streams and uses m3u8.

im gonna fix that watermedia method (in 1.3.6).

**Comment by CreativeMD** [comment]
Hey, thanks a lot for all your work. I wanted to merge it on Monday, but I had other things to do. Same yesterday and today. I'm sorry but I need some time to do the transition properly. That's why I will merge this next week.

**Comment by SrRapero720** [comment]
Ok, dont worry.
I am doing some stuff un watermedia to enhance API and loading performance. So before end this week i'll make extra commits to use /support latest watermedia versión.

**Comment by SrRapero720** [comment]
i just change watermedia version (gradle) and use a better way to identify if watermedia have binaries of current OS (in case watermedia have VLC binaries for macos or linux

**Comment by CreativeMD** [comment]
Released it for 1.19.2, 1.19.4 and 1.20.

**Pull request merged**
